version: '3'

services:
  frontend:
    build: .
    ports:
      - "6500:6500"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - calendar_form_network

  nginx_calendar_form:
    restart: always
    build: ./nginx
    ports:
      - "6501:80"
    depends_on:
      - backend
    networks:
      - calendar_form_network

networks:
  ai-atende-network:
    external: true
